{% set python_min = "3.12" %}

{% set name = "pycalceff" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycalceff-{{ version }}.tar.gz
  sha256: 9288cc05180756f14bd43ddc0d56c20fe76d22910c81f005503ed9b89276d6c5

build:
  entry_points:
    - pycalceff = pycalceff.main:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - typer
    - rich
    - scipy

test:
  imports:
    - pycalceff
  commands:
    - pip check
    - pycalceff --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/marcpaterno/pycalceff
  summary: Calculate binomial efficiencies and their uncertainties
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcpaterno
